name: Agenda_Management
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  table_calendar: ^3.1.1
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  flutter_slidable: ^3.0.1
  custom_sliding_segmented_control: ^1.8.2
  flutter_local_notifications: ^17.1.2
  uuid: ^3.0.6
  timezone: ^0.9.3
  permission_handler: ^10.2.0
  flutter_native_timezone_updated_gradle: ^2.0.3
  syncfusion_flutter_charts: ^25.2.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
